// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCbJkJOYac35FPNuEmA1Kn4da2ufWeNY',
    appId: '1:11399248856:web:b4fd4dd292f00dcfe710ad',
    messagingSenderId: '11399248856',
    projectId: 'email-sever-2d00a',
    authDomain: 'email-sever-2d00a.firebaseapp.com',
    storageBucket: 'email-sever-2d00a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUGoIUVreLQJQSoXrU6wn6PIthNO7vCA',
    appId: '1:11399248856:android:dc52be6d8c2f509ee710ad',
    messagingSenderId: '11399248856',
    projectId: 'email-sever-2d00a',
    storageBucket: 'email-sever-2d00a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtiYac42u0gD_iguwEiYlJFm5RAeBw3AA',
    appId: '1:11399248856:ios:0a9de5712da52908e710ad',
    messagingSenderId: '11399248856',
    projectId: 'email-sever-2d00a',
    storageBucket: 'email-sever-2d00a.firebasestorage.app',
    iosBundleId: 'com.example.ir2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtiYac42u0gD_iguwEiYlJFm5RAeBw3AA',
    appId: '1:11399248856:ios:0a9de5712da52908e710ad',
    messagingSenderId: '11399248856',
    projectId: 'email-sever-2d00a',
    storageBucket: 'email-sever-2d00a.firebasestorage.app',
    iosBundleId: 'com.example.ir2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFCbJkJOYac35FPNuEmA1Kn4da2ufWeNY',
    appId: '1:11399248856:web:29408f67b9264c4ee710ad',
    messagingSenderId: '11399248856',
    projectId: 'email-sever-2d00a',
    authDomain: 'email-sever-2d00a.firebaseapp.com',
    storageBucket: 'email-sever-2d00a.firebasestorage.app',
  );
}
